version: "3.9"

name: "notifee"

services:
  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - "6380:6379"
    command: redis-server --save 20 1 --loglevel warning --requirepass redisDeveloperPW
    volumes:
      - redis:/data

volumes:
  redis:
    driver: local
