# Use the official PostgreSQL Alpine image as a base image
FROM postgres:alpine

# Install curl and envkey-source
RUN apk --no-cache add curl bash && \
  VERSION=$(curl https://envkey-releases.s3.amazonaws.com/latest/envkeysource-version.txt) && \
  curl -s https://envkey-releases.s3.amazonaws.com/envkeysource/release_artifacts/$VERSION/install.sh | bash


ARG ENVKEY
ENV ENVKEY $ENVKEY

# Define an entrypoint to dynamically set PostgreSQL environment variables
ENTRYPOINT ["/bin/bash", "-c", "\
  eval $(envkey-source) && \
  exec docker-entrypoint.sh postgres"]

# Set up health check
HEALTHCHECK --interval=10s --timeout=5s --retries=5 \
  CMD pg_isready
