# Use the official PostgreSQL Alpine image as a base image
FROM postgres:alpine

# Install curl and infisical
RUN apk add --no-cache bash curl && curl -1sLf \
  'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.alpine.sh' | bash \
  && apk add infisical


ARG ENV
ARG PROJECT_ID
ARG INFISICAL_TOKEN

ENV INFISICAL_TOKEN=$INFISICAL_TOKEN
ENV ENV=${ENV:-prod}
ENV PROJECT_ID=${PROJECT_ID:-project_id}

# Define an entrypoint to dynamically set PostgreSQL environment variables
ENTRYPOINT ["/bin/sh", "-c", "infisical run --env=${ENV} --projectId ${PROJECT_ID} -- sh -c 'docker-entrypoint.sh postgres'"]


# Set up health check
HEALTHCHECK --interval=10s --timeout=5s --retries=5 \
  CMD infisical run --env=${ENV} --projectId ${PROJECT_ID} -- pg_isready -U $POSTGRES_USER -d $POSTGRES_DB
