services:
  notifee-redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
      args:
        - ENVKEY=${ENVKEY}
    restart: always
    expose:
      - "6380"
    volumes:
      - redis_data:/data
    networks:
      notifee-network:
        ipv4_address: 172.21.0.11

  notifee-postgresql:
    build:
      context: .
      dockerfile: Dockerfile-postgresql
      args:
        - ENVKEY=${ENVKEY}
    restart: always
    expose:
      - "5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      notifee-network:
        ipv4_address: 172.21.0.12

  notifee-app:
    build:
      context: ../
      dockerfile: Dockerfile
      args:
        - ENVKEY=${ENVKEY}
    image: notifee-app:latest
    restart: always
    depends_on:
      notifee-postgresql:
        condition: service_healthy
      notifee-redis:
        condition: service_healthy
    ports:
      - "3232:3000"
    networks:
      notifee-network:
        ipv4_address: 172.21.0.10

  notifee-scheduler:
    build:
      context: ../tools/scheduler
      dockerfile: Dockerfile
      args:
        - ENVKEY=${ENVKEY}
    image: notifee-scheduler:latest
    restart: always
    networks:
      notifee-network:
        ipv4_address: 172.21.0.13

volumes:
  redis_data:
    driver: local
  postgresql_data:
    driver: local

networks:
  notifee-network:
    driver: bridge
    name: notifee-network
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
