services:
  notifee-redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
      args:
        - INFISICAL_TOKEN=${INFISICAL_TOKEN}
        - ENV=dev
        - PROJECT_ID=1f0d48ee-5f3d-4e85-a6e3-22c282fcb244
    restart: always
    expose:
      - "6380"
    ports:
      - "6380:6380"
    volumes:
      - redis_data:/data
    networks:
      notifee-network:
        ipv4_address: 172.21.0.11

  notifee-postgresql:
    build:
      context: .
      dockerfile: Dockerfile-postgresql
      args:
        - INFISICAL_TOKEN=${INFISICAL_TOKEN}
        - ENV=dev
        - PROJECT_ID=1f0d48ee-5f3d-4e85-a6e3-22c282fcb244
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      notifee-network:
        ipv4_address: 172.21.0.12
volumes:
  redis_data:
    driver: local
  postgresql_data:
    driver: local

networks:
  notifee-network:
    driver: bridge
    name: notifee-network
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
