version: "3.9"

services:
  notifee-redis:
    build:
      context: .
      dockerfile: Dockerfile-redis
      args:
        - ENVKEY=${ENVKEY}
    restart: always
    expose:
      - "6380"
    ports:
      - "6380:6380"
    volumes:
      - notifee_redis:/data
    networks:
      notifee-network:
        ipv4_address: 172.21.0.11

  notifee-postgresql:
    build:
      context: .
      dockerfile: Dockerfile-postgresql
      args:
        - ENVKEY=${ENVKEY}
    restart: always
    expose:
      - "5432"
    ports:
      - "5432:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      notifee-network:
        ipv4_address: 172.21.0.12
volumes:
  notifee_redis:
    driver: local
  postgresql_data:
    driver: local

networks:
  notifee-network:
    driver: bridge
    name: notifee-network
    ipam:
      config:
        - subnet: 172.21.0.0/24
          gateway: 172.21.0.1
